# Generated by Django 3.1.3 on 2020-11-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='iten_price',
            new_name='item_price',
        ),
    ]
