# Generated by Django 3.1.3 on 2020-11-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20201127_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item_table',
            new_name='Item',
        ),
    ]
