# Generated by Django 3.1.4 on 2020-12-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20201127_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Item_frm_model',
        ),
    ]
